version: 0.2

phases:
    build:
        commands:
            - echo Entered the Build phase...
            - mvn clean package
    post_build:
        commands:
            - echo Build Completed successfully
artifacts:
    files:
        - target/medical-representative-schedule-service-0.0.1-SNAPSHOT.jar
    discard-paths: yes
    